condense_wildcard_suffixes = true
enum_discrim_align_threshold = 50
fn_params_layout = "Compressed"
format_code_in_doc_comments = false
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Upper"
imports_granularity = "Module"
max_width = 120
newline_style = "Unix"
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 50
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
